### ISSUE TITLE
How install?

### ISSUE THREAD

**Issue by gperdomor** [lkuczborski/SwiftMoyaCodeGenerator#6]
how can i use this?

**Comment by lkuczborski** [comment]
You need to put the folder here: `~/Library/Containers/com.luckymarmot.Paw/Data/Library/Application Support/com.luckymarmot.Paw/Extensions`. After this, the extension should be visible in Paw extensions dropdown in the app.

**Comment by gperdomor** [comment]
I don't see it in the export content menu, and either in the list of extensions installed :(... I'm using paw 3.0.16

**Comment by lkuczborski** [comment]
Try putting repo contents in a folder named `com.kuczborski.PawExtensions.SwiftMoyaCodeGenerator` and placing it in a folder with other extensions like shown below.

![screen shot 2017-02-22 at 14 41 28](https://cloud.githubusercontent.com/assets/6804537/23213942/3b47585e-f90d-11e6-88eb-2267ab0cd052.png)

If it does not work, you can try `"Reload Installed Extensions"` from `Paw -> Extensions`.

**Comment by gperdomor** [comment]
thanks :D... It's works
